version: '3'

services:
  dev:
    container_name: data_processing

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - ..:/workspace:cached
    
    working_dir: /workspace
    tty: true
    stdin_open: true

